#!/usr/bin/perl -w
use strict;

use lib qw(../blib/lib ./blib/lib);

use Algorithm::MarkovChain;
use Data::Dumper qw/DumperX/;

my $c = Algorithm::MarkovChain::->new();

my $filename = shift || 'README';

open FILE, $filename
  or die "cant open '$filename': $!";

local $/;
my $file = <FILE>;
close FILE;

my @symbols = ($file =~ m/(\S+)/g);

$c->seed(longest => 4,
         symbols => \@symbols);

#poke where we're not invited.
#for my $key (sort { keys %{ $c->{_chains}{$b} } <=> keys %{ $c->{_chains}{$a} } } keys %{ $c->{_chains} }) {
#    print DumperX { $key => $c->{_chains}{$key} };
#}

print join(' ', $c->spew(complete => [ @ARGV ],
                         length=> 20)),"\n";
